language: java
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew check jacocoTestReport publish"
    if: branch = master AND NOT type = pull_request
  - stage: build release
    if: branch =~ /release/
    script: "./gradlew check publish -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: rDzZ22AVg2dodTzMWdjfWgPGiFY1JzpRFr67cHbfWkbvULqHbjW+CLJfM6VAKchlik4ERMqVWEmgJb67xahT0WylUfmOqn+zNVGouXxzLoF6GZtDQPbZ4IpW0bHp4xFnMszWdK/7T0h8nEbOxjDlSojz4de5pCIHDBHxIvpVYqImurqDpzzR2vDYcp83Esk/1WMceOndlmQpAngwPzaAamJPYpPvkNbEtQprfcuDKhiEKicZq91FCGRYV/r7Z5S2JBavk6asKIp77JKtKCgYHFKR1ZaXARX04vDfXYRfkbefmHxATDx9IS8RkNsbO7bgeKck4qKvBOgzELABS/+NS/dpQ2BrPsnTpiZ9mPltNTv3027VfsI4VAAyrn0nNG03O+iDloZNgf4DUTEP5689XFKP2lFaI/kmJN80K4UUS5QSqTgaf/cCZjONWGbds61pxFhczEThdiR/8GOGw88tV+abocBAGgisl1y2OdY0eMKsx8Iw4/yt6D1N+fCngEtALdVMLqgFwG1tcybn28HNUXdHuMosWZI5YHGz+I+GRTG+Zx+qgWwnliXAxIZHHaBPcvYFqxJYm+wYA7beaHp1+XSQn4GgLlGcYrq4++25WrekJO5N+8JKjtSRP1rFQuSYBHVsi4fV/WlXhFngoIPGh4RbrtSfWVoPdxqIAR9ebqY=
  - secure: dr3PqdX4iwWMA5123bUI8nxIXuj2O+CrZ68wCpiF+DfN0TE6H9WuqtmK5EP/pNlRPucgrjS+vO/7kzi4X6UG2qoWSXAvgtRm8p1em8H4uSIIDkm6f5Qk5le5nnbe3pfN2HO0pameQc35lp17Udc2y5zjGnicMCnglqvjlEyUeFcdWX/JHMrDdc+944/6Y5iiemmtW1MaPKh3lgqG2t+YsRRqq1Akhe4j1PLMH4SrFjo+fuipGOrAsCByMJqwoEVy7k6rBaNHwAEJTxnDUUA9vOrE/o8l3qQlfc+swOMUP/Y6ObDnymSm22g94Nl3wwqq810ldrkXvV9Sm18r9hc59LEIhNiNw1rZ6jTExJ+dsSFYxhJYDyOjecaiCzGwlcX65iGxGdUGpDFl9RcDJJPDGVqXYLWgSeQtfIJ/+oZ4VTaAn7YmRMr0jspN3H5H3KSmo1RSJTtN3NMxauB/IxRu9wzcx2pn1cfSKdfAQsLBBDo6fQAOmAM50qVb/bqNG7drnunaz/9HyimRQnGMh9CY05Dch5/s4Uj8yBqyJAsy7ErzimRTc0kdTeDY8SJe46poQuNDZgwUqMgiLXwv2KyM/vCrRW0lGUSy2J1Y+Z5ICGp0YoWvc6H59u4dDL/H2r8ge39/T5bdIG73ekpBo5Dyk+kP1vimSkjUh199PyuYQM0=
  - secure: hatW/tndktWS8heDe33Fnm0eICOCYrckX6Syg9qCG3VYAH7bz2oGa7FTyNsHwFDoiEakzlXCUsDpEqDiJeU3K9Fhu49xKCv6hi2IZ7Ob8/vLYopLEvaXJ3uPTVvoyeY49ZmmttboOCV1zMqxT8NLSqjZb97c9PNgBrtXVr6PGZxBFNfA8XVDVH9EBvkyOhnq4dA7JmMAUNyO0Iig0eUdeVqdp2gPq8AIfdFGaLu8dHSuXsJ0g0vevyi41EEAob00yUugvHcfuU60CoE/L99wwarnA2bVdX3yJkUjNvarilz4O70pcIKkY3MD55IXZzmmBRXuPamoWOybuVhtqiupwp8TBS3rh1cCEjpLRsJA4C5PPXn0/1+KfHwnRR5WvcPsrwczXH/lQha4B7iAcUGw2DX2H1TQzFkHCJijPRgjc9k28/esEJqyquwldxSjJnjr8uAC/uwkVXtNWXXac5i5d5wqSG+OTYlZgG7ZFz2TMS4zGOEMZt1Xie0sEm96bNK+Yz6FA411rd/GtHZIgEpSLmqTNu1Y5/9RX3yGV3MKB8F4A0FfDsaHxiOjHyMtZqiTd6Ljbkt01L934pqfg8LDdLvu5p0PnLc7cYOaRKwDkh1+Oq8w+YRVcTaI9iaSjc743ZeA4OqBDRuCoZgJOAw6X0ykZRQaRkvLD+ilvHALyCc=
  - secure: S2bAbkIR2lSf4R20I0AdRZSY7nLEjuScsztwTe6kiB8AkmfIbLJwTcLvkAxhHWV/ovohJ6s89E8K69mHV1hYJi2V9mZHfFwQjCf6rFO8UPU0SmaTaRLP9iY0iNhltZLZ5XaAojYLOtluen2rnrQzEQY2SanrdoZ7k99zJ9YHNt03p1hLtNQ58FCVovVoPLYZ7ztVWnEz/B0/18jaFA/eUw9cN24FHnJ7yHg83t2QNrah6niVUrjYoqmrvMpvKSxDTWVbqmwQfTD/8yMrNrZ0PpGeBtBOVyKgxM/WlE+XrzAUJMZ+a+7kbyGe99ebj7BMnHD7BYA9Q5w7KdZtu5uYxZTgkI/PWBesCf+4hrCdmB872D8hwEIW0nzhNKROOgztQ5AcnwRC2QPWsHNYKteYcy9XTExYLe9qKC3sCvn4oaic4nY0hADaWICfml8YurDGsLlz9BIFfg+4atfj+LyL5aiqGK8HEc6jYc1lTg++UaPc4wJoRe4ywTLYnthtSCsrDTUq+FPSrj7T09gDRMy+w0n/ZruWot/0DNUPNMukvEo+bkPsqdfZnHYh7bLMaMFhI+eoLn2YHgVnkXCghkiEWWGgTH205RCumac2wknb+MiY6+e4nEWHOtYHlnvFxNkZUNIUDR1zI6EB+YkEKkgeA8ZH0LkM1L0+6x5cL8loMUk=
before_install:
  - |
    if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      openssl aes-256-cbc -K $encrypted_7f20b2c8d0fe_key -iv $encrypted_7f20b2c8d0fe_iv -in web3j.asc.enc -out web3j.asc -d
    fi
