language: java
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew check jacocoTestReport publishMavenPublicationToSonatypeRepository"
    if: branch = master AND NOT type = pull_request
  - stage: build release
    if: branch =~ /release/
    script: "./gradlew check publishMavenPublicationToSonatypeRepository bintrayUpload
      -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_7f20b2c8d0fe_key -iv $encrypted_7f20b2c8d0fe_iv -in web3j.asc.enc -out web3j.asc -d
  fi
env:
  global:
  - secure: Ku+X5nINklnu53B8EuyVXBVyCxw7y94DkksT7Khp9vFztRQiY65dEp2AefLphbMSIBF2fnPdXms1aidcpnd19gCc+ptib2sv8TwfiIFXQr2GeTRIwzcr+IsILPUVOOCO81Fw9QO14S/CSLfjuIMNDTWJ9AEDgI0yG05qC3hpWEbmQbP29a8QFeYD6PB/OizSz0o+ieTOfYdE8d2U5f3/axWA81P6l+3L9CAT3cNY/433O3fJemDTyN0mo1xBN4dLy2zFYWjAs97ehjJMwnWGCnPl0P9sVmTH5mJ6pnDSyAU69KG50h+UA5oWD4a+2TzG8miIcpsgCl5a0Q+MtROw1MTfW1pQAY8GYSrnlovkNHznUB/WKTwmLvM2SOlPr4o1+qhsrIY0l8Ne/y4pQeRY/+Q5XdIpgnW+pOsoCmf/zs4XKT46DcM7xsWuMOGrqBUO8tmLwdGQPntdRrRfr15IdzF2ze0BuRf3R6U5i0gjFA8GGwuKXbma3EgwzvXFAVClbsi+JsC9zXK1LbvZkGCRNGCEGcWkQrb2X4ZToG9v5EScMlzsQ56y7/8NwwcOA3Kj8HU+3dn+gkNHMPI7GfJ3e/f7u9LTqE5ebgNRxvobUR/jambmAr7WOeTtRfu2MeUGoPKlfJATm9zskVGvbJnQPI5dI64d6VVkOgP2DyU9c3I=
  - secure: DMhwHg9HC0DAxgg+Pqh5DIQg4tNPJaXlyNM+ZeNaiVVbW1VvaLDIKlx5ZfTVUlYqJeEQRZY7q2IWWV+Axfucv0iqCAv35if7zPz1d/D8uDOzZ3UB+78U/5vtFYs7oe+6daWV86eTO2the/J4dB/mfSUt2cZuZb8VrOIEbdP4ZUKt5bQZXE9wp/wzhRuHfHfEZnGcm/dmf2V1ECN/eGz5HFOHl3jDFHSGDUP3Indw4q+M6zxqbBFHGFr24XkdfCJ2xdJgeb6tqafmXsr8QR3/j5mhh6ZpAaHPFEEwkqh6eiVLMJUNN3sLcug8xZj41+OUIJu1jhp5BlMnrGmOlM50JcBVqzLSA288JTrrBi3S930gjmCbdOi/FdRx4MLfhmI4uO0jN84+jdO8XdSGvjbyjv1aAFfL+uMoWPWfrIVdfGBmIaX/TArgwfZqp8juXCoEAIwiZYJdVvlWrXvGyB051tmp34YHHTrhe7UxOOAnodsykqweou4fswwiOy0MvBoTc4wHgDEv12FA+E3hfb2PXU37zVbiryHKGqrZLLHD9OCyWP7Bo1gP9sByILlq81cOXEUmYEms46PC3QwRPP9avRw/kcf9lPXR+IcefPyTmuWCjhRyef4JTzCG1IeOcrhEruWCmfAuwPq/NVsSfhG2AuzDzpARtl+OFEwojZ38IwE=
  - secure: tlBGzgyEvMMZxnCoeK0ojOkRf2FsjKHM/Giw5p+eTIZ4cEomDWVASHqslB3dK7ziyfXNyC6wuAf9rihC8nm0gDvvp7qWFcGU22SBIgmILCrAuT80Xr+Dj8GyxN0/q7eznWLxctgkqqCyinDUm05CQ5zmXlC4JXLrC04yRi8SGPZRDu2ThOQayO7CGjVVRno5DKJE9XEa7dXnd6sOdZiOlLavs1NMJJpXxG4hPPngTTngwaoYO0EGrJqKgdxejJkciWldD+TgWoS8F7I4EAgt2qyPVpbwu+pzN6A91hzrLvs0KQQe0kqJtzH0nUzAHD8HXgomc7I/ZUJBgfF1Ux3Xh5znY77gkuaagrb3SgKDq8wkpAWAQrrFEZuFYOBhGz21R4vOv5v9W6UWaYLfEWkknl3IfLIaLxNR5j6zgcxNFNio+K1hVB0o4l30Kgd6rCKbmvf4TTPbnmuN0J9WiR0X5vwJP7i9M3odPDIa8dlCIw/VMzlQrs8SfC6IGspRWoJ7YeiOgYkxgb5zWx0Z9prXtfWypp6QHT+WZVu3APq3O27/TUdf+teKOFp99zTlMG82+cvyT5cVMu41uSaMYVdxEZFT6VYs/Er3cyJVMfGzuZxxWR/XDBVbNPj7Mt/OSqdlUxzBLw/vGf+hAVg2aEGy79DgwZLVVObeV89GR0vchS4=
  - secure: IcI6DoDYY62GcGlNrUpG0hKNJbE1k7tD49WqqnQsVGMTdN2sMxKA44R3FXmX1rGJDVerNeXohp50L+o7CIrdJSGDTJzgvu//IgRNGzLUj4A2d/1feoJ/+xD5JHsTRBjm0Mxh+j9o+U6+jwFEfPcMQvDwEGWnwF5CuhVWUzwbLOhscrBFHdgnNq2fUY39BEA0thrCiAMdLPXSrOvu6Dec2JnRmd/ld+pmaK1Q61Q7wlSc4GKru8iS32yy14zdvVB0EVylC++//1WtPcUllJjXaqWZdryU8SuyfOJXq0rNY7jszOZ+LkZO8IN+DcJXUF3dxH5eGWP+I7fVZjxJrS04QOPELLbmayctgMTNvMgKSpIMXbLL8LGhYxlTEpPQN4GTXjr9taMzr49ypgc9QigX+jBzIEGjAROLuqBt9VJHz3uYqvCZz1SfL3UevDZb0j+bbvQ6slKFsoNLXd62Bjmo8XN3/gMMKkJxu9xZRJRM/kU43NBuhEsztz69w/FX+KvYWUBesOyyX/3cQR2ac/hnGxCeYi422O7xQqbIpTe0yPj147ws6bpBWtTv1cYW2de1iEzygnQadqu99YfDX0IAjhiRmeReBrbYdYP9DQMc0Mt0djY9apRfqNw8xCM2EcvmR6DECkpcOSHEyNgsirzVhSJRJTE0Whb4P9f2rmrqfnI=
  - secure: Jp9kjOauqpMEcJfBIXFsPlnEOtDFIzNrwhc2VWl/GJTZ9xs6jEH67BQciRnD907W6KvI9kVbJ+ecTfFQF4TlWxgta4hbKbJrzWajMiAcrs5l1jMelowqSmxuGF082t8oRlm98YuwyFRyNvjlG0tBFOZX0i/wXQlx1YQ/AYmbYx4cXcyyP01aN00kjkQ/NO9jHrAh64LyheySTeYPupg+tX1D57W3L9K4P4wDl9VvIRAv6Kq4C9EunSTd5Ulz4iDJTT7NmVt0/tnbwwMy+MH+Fhtgf8cdPHJJwx0kfM28AmN496Up8+9a/KhdAlzvamBhc8xbcEPFkti4LFJQu05c3YJG9Mdsrqr9zLGLMgmbrmLZ1DC4RHu/SSm1wI2KcQg63LU7egQgTJxC+TP3ljorAtziVdCs3NbWqSeV3T/9+7UIW1Hzx85669rqLgEfqDb5TTYOWV6/jEeBZ6a/IBLflFNIzUrbpma23sztsjBmlzeOpQ/amL94YyPjIvJ+IJY4Yg6tqIiAMZ37M5wMGWH1W4pzQMANZ0+TewGBo/rEDPFgs6Hu1v84B/3yUNYuHo/s4QQ5Ux5219ooUaR8Z/c0MQJC+WdF4w3X3XOzLVJKg+TVFcy1v5/W70evOudtVeyL3gOl+5Y8fRRlnXXfxP5GKac/ECiyP/uMg3VxMWKLitk=
  - secure: uLxx4zdYn59P4GrewFIMdEDmfVXTsIUK7jsRV/zhJaf3OQSnwLX/Q6w39qPRGEpT0Jnn7p+OG+5NGCYnG8l3aJTkYRmmpyaNrhYq8CDF7s/YWr04/d0Nj6e20ijKeFgfsGY+pn31ScMEeArBX+SKcN1FafzW6CW1HjYQb7unUliElj9fWh+BBRZV/PO1FD0yAZfjjVvov/MLTjeJao8v5dcKvsGRf2ovmLsCHZP0CnwkzDYrngCGqu4lfJeHE6RZsXOlRiviuky4B08u82Sqe38zP+yC2pizPTHt1+Ww4hz69uYfeNYJhzqfV7xAJxjsT5PfFWRSDFbhsFPhSVNOilhGord4azIeDqey8HxVJszPYMZTtTPVvFZMSJxVbQbGAYWAurYlJ4RTmUmVJx6BcdYgPpkyQeUOMur8YzAd12ay2G6ZnF2D1aJohmWiegRB1sX/015ljrjGR9cz32gVqOTJcMdv/aHHzt2bG09cPA0Zsdgpin8OWqB2cbtTSNvkMuTQqQRAMNVh4Bx3peqBDmNKCqzg9m79aRB+eoMlYuht3UgN260ISCktTBkaQBqIcIyH8/dPHOFhPLOgcYOHpPqrLRhn8vzhmQPFBu6lcsWFffFKJI3vzkPlaCl5wox9OjlXRjPEII1wGcpCUGJItIloIixdmuPfv2Ip6Y/1CW0=
